feat: Add Compare Triplet HackerRank Js Coding Challenge
moshoodabdullahi/js-coding-challenges pull request #12
Opened 2023-11-19 16:32 UTC by moshoodabdullahi

# This PR adds the compare triplet hackerRank js coding challenge

2023-11-20 20:18 UTC, Yinkusadel commented
you should add the link to the challenge on your PR description

2023-11-20 20:19 UTC, Yinkusadel reviewed
you should add the link to the challenge in your PR description

2023-11-20 20:57 UTC, Yinkusadel approved these changes, later dismissed
nice

2023-11-20 22:01 UTC, teckcipher approved these changes

2023-11-20 22:01 UTC, teckcipher commented on .eslintrc.json
> +    "no-unused-vars": "warn",
Please remove this

2023-11-20 22:04 UTC, teckcipher requested changes

2023-11-20 22:04 UTC, teckcipher commented on hackerRank/compare-the-triplets/compare-the-triplets.js
> +  for (let i = 0; i < 3; i++) {
Let's chnage the `i++` to `i += 1`

2023-11-22 05:59 UTC, moshoodabdullahi commented on .eslintrc.json
> +    "no-unused-vars": "warn",
Done

2023-11-22 05:59 UTC, moshoodabdullahi commented on hackerRank/compare-the-triplets/compare-the-triplets.js
> +  for (let i = 0; i < 3; i++) {
Done

2023-11-23 14:01 UTC, Yinkusadel approved these changes
Ok

2023-11-28 05:39 UTC, teckcipher approved these changes

2023-11-28 17:07 UTC, merged